name = "worker-app-1"
main = "src/index.ts"
compatibility_date = "2025-02-18"

# Environment Variables
[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZThhMGMwMTYtOTU1OC00OWNkLTkwZTQtMTZlY2E3MzY0MTczIiwidGVuYW50X2lkIjoiNjM3YjQyYzM5NDM0MWRhYWJhM2IzMTNiYjVjZDBiNmE3MWRhOWZkMWM3ZjFmZGZmNDBhZmVhMzIzZDI2ZjA0ZCIsImludGVybmFsX3NlY3JldCI6IjI4MzZmMGYxLWMwOGItNGVlMS1hZTU5LTZmOGYxMTQxZTQxYyJ9.s5xYZ2MZAALByfvAmmtf9XnGmFBpVEhTkIJbunf3e3k"
DIRECT_URL = "postgresql://neondb_owner:npg_mWvpC4hfd1IL@ep-sparkling-feather-a1m6xc69-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
JWT_TOKEN = "AdityaKanthe"
